project_id = "chgbzcsbwmfpyucqbhmb"

[functions.groups]
verify_jwt = true

[functions.group-members]
verify_jwt = true

[functions.group-favorites]
verify_jwt = true

[functions.feedback-series]
verify_jwt = true